states = {
    'al' : 'alabama',
	'ak' : 'alaska',
	'az' : 'arizona',
	'ar' : 'arkansas',
	'ca' : 'california',
	'co' : 'colorado',
	'ct' : 'connecticut',
	'de' : 'delaware',
	'dc' : 'district of columbia',
	'fl' : 'florida',
	'ga' : 'georgia',
	'hi' : 'hawaii',
	'id' : 'idaho',
	'il' : 'illinois',
	'in' : 'indiana',
	'ia' : 'iowa',
	'ks' : 'kansas',
	'ky' : 'kentucky',
	'la' : 'louisiana',
	'me' : 'maine',
	'md' : 'maryland',
	'ma' : 'massachusetts',
	'mi' : 'michigan',
	'mn' : 'minnesota',
	'ms' : 'mississippi',
	'mo' : 'missouri',
	'mt' : 'montana',
	'ne' : 'nebraska',
	'nv' : 'nevada',
	'nh' : 'new hampshire',
	'nj' : 'new jersey',
	'nm' : 'new mexico',
	'ny' : 'new york',
	'nc' : 'north carolina',
	'nd' : 'north dakota',
	'oh' : 'ohio',
	'ok' : 'oklahoma',
	'or' : 'oregon',
	'pa' : 'pennsylvania',
	'ri' : 'rhode island',
	'sc' : 'south carolina',
	'sd' : 'south dakota',
	'tn' : 'tennessee',
	'tx' : 'texas',
	'ut' : 'utah',
	'vt' : 'vermont',
	'wa' : 'washington',
	'wv' : 'west virginia',
	'va' : 'virginia',
	'wi' : 'wisconsin',
	'wy' : 'wyoming',
	'gu' : 'guam',
	'mp' : 'mariana islands',
	'pr' : 'puerto rico',
	'ci' : 'circuit courts',
	'vi' : 'virgin islands'
}

for key in states:
    code = key.upper() 
    state = states[key].title()
    print('{}.{}. is the code for {}'.format(code[0],code[1],state))